# -*- coding: utf-8 -*-
"""math_operation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18e2AIZBIPkH0CvVes5uEcJhTDskhhKYr

add abd subract
"""

def add(val1,val2):
  return val1 + val2

def subract(val1,val2):
  return val1 - val2

def multiply(val1,val2):
  return val1 * val2

def divide(val1,val2):
  return val1 / val2